name = "openposta-worker"
main = "worker.js"
compatibility_date = "2025-05-30"

[vars]
RESEND_API_KEY = "re_5rJ4fccM_4jWaTzBwv6WEzWunWnhkTbqy"

# 绑定 D1 数据库
[[d1_databases]]
binding = "DB"  # 对应代码中 env.DB
database_name = "email"  # 你在 Cloudflare 上的 D1 数据库名称
database_id = "37470a3e-fc7c-430c-a0f7-d1674dfaa96c"  # 可在 D1 控制台查看
